name: Build Blender iOS

on:
  workflow_dispatch:

jobs:
  build_ios:
    runs-on: macos-latest
    steps:
      - uses: actions/upload-artifact@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          brew install git-lfs cmake python

      - name: Initialize Git LFS
        run: git lfs install

      - name: Pull Blender LFS
        run: git lfs pull

      - name: Update Blender iOS branch
        run: ./build_files/utils/make_update.py --use-ios-libraries

      - name: Build Blender for iOS
        run: |
          cmake -B build_ios -DCMAKE_TOOLCHAIN_FILE=build_files/cmake/toolchains/iOS.cmake
          cmake --build build_ios --config Release

      - name: Archive and export IPA
        run: |
          xcodebuild -workspace build_ios/Blender.xcworkspace \
                     -scheme Blender \
                     -configuration Release \
                     -sdk iphoneos \
                     -archivePath build_ios/Blender.xcarchive archive
          xcodebuild -exportArchive \
                     -archivePath build_ios/Blender.xcarchive \
                     -exportOptionsPlist build_files/utils/iOSExportOptions.plist \
                     -exportPath build_ios/ipa

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: blender-ios-ipa
          path: build_ios/ipa
